### PR TITLE
Add back in the button styling and view height

### PR DESCRIPTION
**Pull request by janitastic**
Hi Rachel,

If you get a chance, can you please review our project code and share your feedback via github?

Thank you!

### Refactor checklist 

- Check variable and parameter names: are they descriptive and unique?

- Is the code DRY? SRP?

- Is it easy for others to read your code? (explanatory comments needed?)

- Is the syntax consistent? (e.g. use of semicolons, blank lines)

- Are commit messages formatted correctly?

### CODE REVIEW

**Comment by rwilliams659** [comment]
- In main.js, you have a lot of event listeners tied to individual small elements. Instead, it's best to have 1 or 2 event listeners for each event type (click, keyup etc) placed on the parent element that encapsulates all of the child ones that currently have event listeners (because events will bubble up to parent elements.) The event handlers for those listeners will be something like handleClick/handleKeyup that then further identify what the specific element clicked/typed in was and calls the appropriate event handlers from there. If this is unclear lmk! Edit: I see you've done some event delegation but I think you can do a bit more!

**Comment by rwilliams659** [comment]
The `buildHtml` function is quite long - You might want to split it up by having 1 function determine the values of `star`, `comments`, `commentTitle` and then passing all of those values as parameters (along with the idea i.e. `filteredIdeas[index]`) into a 2nd function that builds the `ideaCardHTML` - This will be more SRP and overall easier to read

**Comment by rwilliams659** [comment]
In your Idea class, I suggest you change the name of  the `updateIdea` function to be more semantic. Additionally, I'm not sure the local storage functions belong within the class. Functions that belong within a class should really deal with adding to or changing properties of that class, which those functions don't really do. For example, it might be good to add a function in that class for `addComment` that you could call rather than manually accessing the comments array for an idea and pushing it in.

**Comment by rwilliams659** [comment]
For the Comment class, I'm not really sure why you have separate local storage functions within that class; since comments are part of the Idea class, when each Idea is saved to/deleted from local storage, it should already include the comments array. (From what I can see, you aren't actually using those functions)

**Comment by rwilliams659** [comment]
Overall, nice job with this - hopefully these comments are helpful and feel free to reach out if anything is unclear/you need any help!

**Comment by janitastic** [comment]
> * In main.js, you have a lot of event listeners tied to individual small elements. Instead, it's best to have 1 or 2 event listeners for each event type (click, keyup etc) placed on the parent element that encapsulates all of the child ones that currently have event listeners (because events will bubble up to parent elements.) The event handlers for those listeners will be something like handleClick/handleKeyup that then further identify what the specific element clicked/typed in was and calls the appropriate event handlers from there. If this is unclear lmk! Edit: I see you've done some event delegation but I think you can do a bit more!



> Overall, nice job with this - hopefully these comments are helpful and feel free to reach out if anything is unclear/you need any help!

Thank you!

**Comment by annamkummer** [comment]
> * In main.js, you have a lot of event listeners tied to individual small elements. Instead, it's best to have 1 or 2 event listeners for each event type (click, keyup etc) placed on the parent element that encapsulates all of the child ones that currently have event listeners (because events will bubble up to parent elements.) The event handlers for those listeners will be something like handleClick/handleKeyup that then further identify what the specific element clicked/typed in was and calls the appropriate event handlers from there. If this is unclear lmk! Edit: I see you've done some event delegation but I think you can do a bit more!

Thank you for this note! We will definitely keep it in mind going forward.

**Comment by annamkummer** [comment]
> For the Comment class, I'm not really sure why you have separate local storage functions within that class; since comments are part of the Idea class, when each Idea is saved to/deleted from local storage, it should already include the comments array. (From what I can see, you aren't actually using those functions)

Good call out, thanks! These are required in the spec, but we agree that they aren't useful in the way we have built this out, so we're not using them for now.

**Comment by annamkummer** [comment]
> In your Idea class, I suggest you change the name of the `updateIdea` function to be more semantic. Additionally, I'm not sure the local storage functions belong within the class. Functions that belong within a class should really deal with adding to or changing properties of that class, which those functions don't really do. For example, it might be good to add a function in that class for `addComment` that you could call rather than manually accessing the comments array for an idea and pushing it in.

Thank you! These functions are required in the spec, so we're not able to change them.

**Comment by annamkummer** [comment]
> The `buildHtml` function is quite long - You might want to split it up by having 1 function determine the values of `star`, `comments`, `commentTitle` and then passing all of those values as parameters (along with the idea i.e. `filteredIdeas[index]`) into a 2nd function that builds the `ideaCardHTML` - This will be more SRP and overall easier to read

Thanks for these ideas! We've updated accordingly.

**Comment by Jayquintana** [comment]
Good job team!

**Pull request merged**
